### ISSUE TITLE
Trick to make clock responsive (css)

### ISSUE THREAD

**Issue by danielarbo** [wojtekmaj/react-clock#22]
Hi!

I leave a css trick to make react-clock responsive.

```html
  <React.Fragment className={'container'}>
    <Clock value={value}/>
  </React.Fragment>
```

```css
.container {
  width: 300px;
}

.react-clock {
  width: inherit !important;
  padding-top: 100%;
}
```

I hope you find it useful and thanks for your work.
