### ISSUE TITLE
Clock does not print

### ISSUE THREAD

**Issue by reductio-ad-absurdum** [wojtekmaj/react-clock#29]
Thank you for this component!

When printing a webpage where clocks are displayed, the clocks do not print correctly, only their outline is printed.

A simple fix is to add the following css:
```css
  .react-clock {
    -webkit-print-color-adjust: exact;
    color-adjust: exact !important; 
  }
```
I have tested it with Chrome and Firefox.
