### ISSUE TITLE
How does one get the same styling as the demo?

### ISSUE THREAD

**Issue by plamenh** [wojtekmaj/react-clock#9]
I looked through the documentation, but it's not there. Specifically the white border, the size of the border, the red circle of the second hand, and the fluid second hand movement. Any chance the dev can share the settings?

Thanks.

**Comment by wojtekmaj** [comment]
Sure!
This is the config I use:

```jsx
        <Clock
          hourHandLength={60}
          hourHandOppositeLength={20}
          hourHandWidth={8}
          hourMarksLength={20}
          hourMarksWidth={8}
          minuteHandLength={90}
          minuteHandOppositeLength={20}
          minuteHandWidth={6}
          minuteMarksWidth={3}
          secondHandLength={75}
          secondHandOppositeLength={25}
          secondHandWidth={3}
          size={250}
          value={value}
        />
```

And here are the styles:

```less

.react-clock {
  background-color: white;
  border-radius: 50%;

  &__face {
    border: 3px solid white;
  }

  &__second-hand {
    transition: transform cubic-bezier(.68,0,.27,1.55) 0.2s;

    &__body {
      &:before {
        content: '';
        display: block;
        width: 7px;
        height: 7px;
        position: absolute;
        bottom: 20%;
        left: 50%;
        background-color: red;
        border-radius: 50%;
        transform: translateX(-50%) translateY(-50%);
      }

      &:after {
        content: '';
        display: block;
        width: 20px;
        height: 20px;
        position: absolute;
        top: 0;
        left: 50%;
        background-color: red;
        border-radius: 50%;
        transform: translateX(-50%);
      }
    }
  }
}
```
